<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxrxI5c\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxrxI5c/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDxrxI5c.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDxrxI5c\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDxrxI5c\App_KernelProdContainer([
    'container.build_hash' => 'DxrxI5c',
    'container.build_id' => 'eceec926',
    'container.build_time' => 1609764080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxrxI5c');
