<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'app_contact_sendemail' => [[], ['_controller' => 'App\\Controller\\ContactController::sendEmail'], [], [['text', '/email']], [], []],
    'twig' => [[], ['_controller' => 'App\\Controller\\ExerciceController::index'], [], [['text', '/twig']], [], []],
    'twig_exercice' => [[], ['_controller' => 'App\\Controller\\ExerciceController::exercice'], [], [['text', '/twig-exercice']], [], []],
];
