<?php

namespace Container023H5nO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OJX3zfjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OJX3zfj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OJX3zfj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.Gv2EfU_', 'get_ServiceLocator_Gv2EfUService', true],
            'App\\Controller\\ContactProController::contactProAdmin' => ['privates', '.service_locator.ZSz72t5', 'get_ServiceLocator_ZSz72t5Service', true],
            'App\\Controller\\ContactProController::index' => ['privates', '.service_locator.Gv2EfU_', 'get_ServiceLocator_Gv2EfUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.Gv2EfU_', 'get_ServiceLocator_Gv2EfUService', true],
            'App\\Controller\\ContactProController:contactProAdmin' => ['privates', '.service_locator.ZSz72t5', 'get_ServiceLocator_ZSz72t5Service', true],
            'App\\Controller\\ContactProController:index' => ['privates', '.service_locator.Gv2EfU_', 'get_ServiceLocator_Gv2EfUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\ContactProController::contactProAdmin' => '?',
            'App\\Controller\\ContactProController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\ContactProController:contactProAdmin' => '?',
            'App\\Controller\\ContactProController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
