<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAide3ID\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAide3ID/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAide3ID.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAide3ID\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAide3ID\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aide3ID',
    'container.build_id' => '283390c5',
    'container.build_time' => 1609846678,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAide3ID');
