<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container023H5nO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container023H5nO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container023H5nO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container023H5nO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container023H5nO\App_KernelDevDebugContainer([
    'container.build_hash' => '023H5nO',
    'container.build_id' => 'a25a9600',
    'container.build_time' => 1609926225,
], __DIR__.\DIRECTORY_SEPARATOR.'Container023H5nO');
